version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: switchfy-nginx
    restart: unless-stopped
    ports:
      - '3007:80'
    networks:
      - switchfy-net
      - coolify
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - traefik.http.services.switchfy-nginx.loadbalancer.server.port=80
      # Route for *.switchfy.ma subdomains
      - 'traefik.http.routers.switchfy-wildcard.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.switchfy.ma`)'
      - traefik.http.routers.switchfy-wildcard.priority=10
      - traefik.http.routers.switchfy-wildcard.entrypoints=https
      - traefik.http.routers.switchfy-wildcard.tls=true
      - traefik.http.routers.switchfy-wildcard.service=switchfy-nginx
      # Route for *.staging.switchfy.ma subdomains
      - 'traefik.http.routers.switchfy-staging-wildcard.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.staging.switchfy.ma`)'
      - traefik.http.routers.switchfy-staging-wildcard.priority=10
      - traefik.http.routers.switchfy-staging-wildcard.entrypoints=https
      - traefik.http.routers.switchfy-staging-wildcard.tls=true
      - traefik.http.routers.switchfy-staging-wildcard.service=switchfy-nginx

networks:
  switchfy-net:
    driver: bridge
  coolify:
    external: true
