server {
    listen 80;
    server_name *.switchfy.ma;

    location / {
        if ($host ~* ^(.+)\.switchfy\.ma$) {
            proxy_pass http://app:5000/$1;
        }

        proxy_pass http://app:5000;
    }
}