server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index 404.html;

    location / {
        # Force l'affichage du fichier 404.html pour TOUTES les URLs
        try_files /404.html =404;
    }

    # Optionnel : s'assurer que les assets (images/css) fonctionnent si vous en ajoutez
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }
}
