# À placer dans le bloc 'http' ou avant vos blocs 'server'
log_format fallback_format '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" '
                           'Host: "$http_x_forwarded_host"'; # Important pour voir le domaine réel

server {
    listen 80;
    server_name _; # Capture tout ce qui arrive sur ce conteneur

    # Utilisation du log personnalisé
    access_log /var/log/nginx/fallback_access.log fallback_format;
    error_log /var/log/nginx/fallback_error.log;

    root /usr/share/nginx/html;
    index 404.html;

    location / {
        try_files /404.html =404;
    }
}

